image: gradle:7.1-jdk11

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GET_STRATEGY: clone

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME='pwd'/.gradle

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
  tags:
    - dalfcs_docker_kvm

test:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml
  tags:
    - dalfcs_docker_kvm

deploy_staging:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - develop
  tags:
    - dalfcs_docker_kvm

deploy_prod:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master
  tags:
    - dalfcs_docker_kvm